### ISSUE TITLE
Use pypi Carolina/Dakota wheels instead of building Dakota

### ISSUE THREAD

**Issue by yngve-sk** [Statoil/carolina#61]
Wheels are building. What remains 2DO is to use the wheel instead of building Dakota etc.

- [x] [Publish MacOS and Linux wheels with the workflow](https://github.com/equinor/Carolina/issues/64)
- [x] [Use pip install Carolina in Everest workflows](https://github.com/equinor/everest/issues/2150)
- [x] [Use standard installation of Carolina on Komodo](https://github.com/equinor/komodo-releases/issues/4664)
- [x] [Add proper Carolina versioning wrt Seba,Boost&Dakota version updates](https://github.com/equinor/Carolina/issues/63)
